# Impoort Libraries

In [12]:
from pathlib import Path
import pandas as pd
%pip install sqlalchemy psycopg2-binary

# Create a Python notebook

In [1]:
raw_folder = Path(r"D:\Data_Projects\airline_delays_project\data\raw")

files = sorted(raw_folder.glob("*.csv"))

for file in files:
    print(file.name, f"{file.stat().st_size / 1024**2:.1f} MB")

flights_2024_01.csv 116.6 MB
flights_2024_02.csv 110.6 MB
flights_2024_03.csv 126.7 MB

# Check for all three months

In [5]:
from pathlib import Path
import pandas as pd

raw_folder = Path(r"D:\Data_Projects\airline_delays_project\data\raw")

expected_columns = None

for month in (1, 2, 3):
    file = raw_folder / f"flights_2024_{month:02d}.csv"
    columns = pd.read_csv(file, nrows=0).columns.tolist()

    if expected_columns is None:
        expected_columns = columns

    print(
        file.name,
        "| Columns:", len(columns),
        "| Headers match:", columns == expected_columns,
        "| NAS_DELAY present:", "NAS_DELAY" in columns
    )

flights_2024_01.csv | Columns: 41 | Headers match: True | NAS_DELAY present: True
flights_2024_02.csv | Columns: 41 | Headers match: True | NAS_DELAY present: True
flights_2024_03.csv | Columns: 41 | Headers match: True | NAS_DELAY present: True

# Inspect monthly

In [2]:
df_sample = pd.read_csv(
    raw_folder / "flights_2024_01.csv",
    nrows=1000
)

print("Sample shape:", df_sample.shape)
print("Columns:", df_sample.columns.tolist())

df_sample.head()

Sample shape: (1000, 41)
Columns: ['YEAR', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE', 'OP_UNIQUE_CARRIER', 'OP_CARRIER_AIRLINE_ID', 'TAIL_NUM', 'OP_CARRIER_FL_NUM', 'ORIGIN_AIRPORT_ID', 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR', 'DEST_AIRPORT_ID', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'TAXI_OUT', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY']

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2024,1,1,1,1/1/2024 12:00:00 AM,9E,20363,N131EV,5225,10397,...,0.0,61.0,48.0,33.0,164.0,NaN,NaN,NaN,NaN,NaN
1,2024,1,1,1,1/1/2024 12:00:00 AM,9E,20363,N132EV,5115,11433,...,0.0,135.0,106.0,89.0,651.0,NaN,NaN,NaN,NaN,NaN
2,2024,1,1,1,1/1/2024 12:00:00 AM,9E,20363,N132EV,5414,11423,...,0.0,111.0,108.0,87.0,533.0,NaN,NaN,NaN,NaN,NaN
3,2024,1,1,1,1/1/2024 12:00:00 AM,9E,20363,N133EV,5284,12953,...,0.0,150.0,129.0,103.0,722.0,NaN,NaN,NaN,NaN,NaN
4,2024,1,1,1,1/1/2024 12:00:00 AM,9E,20363,N133EV,5341,10994,...,0.0,118.0,104.0,83.0,641.0,NaN,NaN,NaN,NaN,NaN

In [3]:
df_sample = pd.read_csv(
    raw_folder / "flights_2024_02.csv",
    nrows=1000
)

print("Sample shape:", df_sample.shape)
print("Columns:", df_sample.columns.tolist())

df_sample.head()

Sample shape: (1000, 41)
Columns: ['YEAR', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE', 'OP_UNIQUE_CARRIER', 'OP_CARRIER_AIRLINE_ID', 'TAIL_NUM', 'OP_CARRIER_FL_NUM', 'ORIGIN_AIRPORT_ID', 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR', 'DEST_AIRPORT_ID', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'TAXI_OUT', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY']

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2024,2,1,4,2/1/2024 12:00:00 AM,9E,20363,N131EV,4867,10208,...,0.0,75.0,84.0,31.0,143.0,NaN,NaN,NaN,NaN,NaN
1,2024,2,1,4,2/1/2024 12:00:00 AM,9E,20363,N131EV,5043,10397,...,0.0,120.0,102.0,83.0,563.0,NaN,NaN,NaN,NaN,NaN
2,2024,2,1,4,2/1/2024 12:00:00 AM,9E,20363,N131EV,5043,14783,...,0.0,111.0,103.0,79.0,563.0,NaN,NaN,NaN,NaN,NaN
3,2024,2,1,4,2/1/2024 12:00:00 AM,9E,20363,N131EV,5049,10397,...,0.0,121.0,112.0,91.0,589.0,NaN,NaN,NaN,NaN,NaN
4,2024,2,1,4,2/1/2024 12:00:00 AM,9E,20363,N131EV,5312,15607,...,0.0,80.0,66.0,47.0,208.0,0.0,0.0,0.0,0.0,226.0

In [4]:
df_sample = pd.read_csv(
    raw_folder / "flights_2024_03.csv",
    nrows=1000
)

print("Sample shape:", df_sample.shape)
print("Columns:", df_sample.columns.tolist())

df_sample.head()

Sample shape: (1000, 41)
Columns: ['YEAR', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE', 'OP_UNIQUE_CARRIER', 'OP_CARRIER_AIRLINE_ID', 'TAIL_NUM', 'OP_CARRIER_FL_NUM', 'ORIGIN_AIRPORT_ID', 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR', 'DEST_AIRPORT_ID', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'TAXI_OUT', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY']

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2024,3,1,5,3/1/2024 12:00:00 AM,9E,20363,N131EV,4841,12953,...,0.0,86.0,77.0,55.0,269.0,NaN,NaN,NaN,NaN,NaN
1,2024,3,1,5,3/1/2024 12:00:00 AM,9E,20363,N131EV,4936,10599,...,0.0,144.0,133.0,115.0,866.0,2.0,0.0,0.0,0.0,41.0
2,2024,3,1,5,3/1/2024 12:00:00 AM,9E,20363,N131EV,4936,12953,...,0.0,182.0,157.0,139.0,866.0,57.0,0.0,0.0,0.0,0.0
3,2024,3,1,5,3/1/2024 12:00:00 AM,9E,20363,N131EV,5099,11057,...,0.0,118.0,108.0,81.0,544.0,NaN,NaN,NaN,NaN,NaN
4,2024,3,1,5,3/1/2024 12:00:00 AM,9E,20363,N132EV,5084,11433,...,0.0,86.0,83.0,60.0,374.0,NaN,NaN,NaN,NaN,NaN

# Correct and verify data format transformed

In [6]:
raw_folder = Path(r"D:\Data_Projects\airline_delays_project\data\raw")

for month in (1, 2, 3):
    file = raw_folder / f"flights_2024_{month:02d}.csv"

    row_count = 0
    wrong_month = 0
    invalid_dates = 0
    earliest_date = None
    latest_date = None

    for chunk in pd.read_csv(
        file,
        usecols=["YEAR", "MONTH", "FL_DATE"],
        chunksize=100_000
    ):
        
        dates = pd.to_datetime(
            chunk["FL_DATE"],
            format="%m/%d/%Y %I:%M:%S %p",
            errors="coerce"
        )
        row_count += len(chunk)
        invalid_dates += int(dates.isna().sum())

        correct_period = (
            chunk["YEAR"].eq(2024)
            & chunk["MONTH"].eq(month)
            & dates.dt.year.eq(2024)
            & dates.dt.month.eq(month)
        )
        wrong_month += int((~correct_period).sum())

        valid_dates = dates.dropna()

        if not valid_dates.empty:
            chunk_min = valid_dates.min()
            chunk_max = valid_dates.max()

            earliest_date = (
                chunk_min if earliest_date is None
                else min(earliest_date, chunk_min)
            )
            latest_date = (
                chunk_max if latest_date is None
                else max(latest_date, chunk_max)
            )

    print(f"\nFile: {file.name}")
    print(f"Total rows: {row_count:,}")
    print(f"Date range: {earliest_date} → {latest_date}")
    print(f"Invalid dates: {invalid_dates:,}")
    print(f"Rows outside expected period: {wrong_month:,}")

File: flights_2024_01.csv
Total rows: 547,271
Date range: 2024-01-01 00:00:00 → 2024-01-31 00:00:00
Invalid dates: 0
Rows outside expected period: 0

File: flights_2024_02.csv
Total rows: 519,221
Date range: 2024-02-01 00:00:00 → 2024-02-29 00:00:00
Invalid dates: 0
Rows outside expected period: 0

File: flights_2024_03.csv
Total rows: 591,767
Date range: 2024-03-01 00:00:00 → 2024-03-31 00:00:00
Invalid dates: 0
Rows outside expected period: 0

# Create the connection

In [ ]:
from pathlib import Path
from getpass import getpass

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

raw_folder = Path(r"D:\Data_Projects\airline_delays_project\data\raw")

username = input("PostgreSQL username: ").strip()
password = getpass("PostgreSQL password: ")

connection_url = URL.create(
    "postgresql+psycopg2",
    username=username,
    password=password,
    host="localhost",
    port=5432,
    database="airline_delays"
)

engine = create_engine(connection_url)
del password

with engine.connect() as connection:
    print("Connected to:", connection.execute(
        text("SELECT current_database()")
    ).scalar_one())

# Load the three CSVs into airline.raw_flights

In [ ]:
text_columns = [
    "OP_UNIQUE_CARRIER", "TAIL_NUM", "OP_CARRIER_FL_NUM",
    "ORIGIN", "ORIGIN_CITY_NAME", "ORIGIN_STATE_ABR",
    "DEST", "DEST_CITY_NAME", "DEST_STATE_ABR",
    "CRS_DEP_TIME", "DEP_TIME", "CRS_ARR_TIME", "ARR_TIME",
    "CANCELLATION_CODE"
]

expected_counts = {
    1: 547_271,
    2: 519_221,
    3: 591_767
}

with engine.begin() as connection:
    existing_rows = connection.execute(
        text("SELECT COUNT(*) FROM airline.raw_flights")
    ).scalar_one()

    if existing_rows != 0:
        raise ValueError(
            f"Import stopped: raw_flights already contains "
            f"{existing_rows:,} rows."
        )

    expected_headers = None

    for month, expected_count in expected_counts.items():
        file = raw_folder / f"flights_2024_{month:02d}.csv"
        loaded = 0

        for chunk in pd.read_csv(
            file,
            dtype={column: "string" for column in text_columns},
            chunksize=50_000,
            low_memory=False
        ):
            headers = chunk.columns.tolist()

            if expected_headers is None:
                expected_headers = headers

            if headers != expected_headers or len(headers) != 41:
                raise ValueError(f"Unexpected columns in {file.name}")

            dates = pd.to_datetime(
                chunk["FL_DATE"],
                format="%m/%d/%Y %I:%M:%S %p",
                errors="raise"
            )

            correct_period = (
                chunk["YEAR"].eq(2024)
                & chunk["MONTH"].eq(month)
                & dates.dt.year.eq(2024)
                & dates.dt.month.eq(month)
            )

            if not correct_period.all():
                raise ValueError(f"Unexpected period in {file.name}")

            chunk["FL_DATE"] = dates.dt.date
            chunk.columns = chunk.columns.str.lower()

            chunk.to_sql(
                name="raw_flights",
                con=connection,
                schema="airline",
                if_exists="append",
                index=False,
                chunksize=1_000,
                method="multi"
            )

            loaded += len(chunk)

        if loaded != expected_count:
            raise ValueError(
                f"{file.name}: expected {expected_count:,} rows, "
                f"found {loaded:,}."
            )

        print(f"{file.name}: {loaded:,} rows staged")

print("Import committed successfully.")